var Base64={DIGITS:"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/",encode:function(a){if(/([^\u0000-\u00ff])/.test(a))throw Error("Can't base64 encode non-ASCII characters.");for(var d=this.DIGITS,b=0,c,e,f,g=[];b<a.length;){c=a.charCodeAt(b);f=b%3;switch(f){case 0:g.push(d.charAt(c>>2));break;case 1:g.push(d.charAt((e&3)<<4|c>>4));break;case 2:g.push(d.charAt((e&15)<<2|c>>6)),g.push(d.charAt(c&63))}e=c;b++}f==0?(g.push(d.charAt((e&3)<<4)),g.push("==")):f==1&&(g.push(d.charAt((e&
15)<<2)),g.push("="));return g.join("")},decode:function(a){a=a.replace(/\s/g,"");if(!/^[a-z0-9\+\/\s]+\={0,2}$/i.test(a)||a.length%4>0)throw Error("Not a base64-encoded string.");for(var d=this.DIGITS,b,c,e,f=0,g=[],a=a.replace(/=/g,"");f<a.length;){b=d.indexOf(a.charAt(f));e=f%4;switch(e){case 1:g.push(String.fromCharCode(c<<2|b>>4));break;case 2:g.push(String.fromCharCode((c&15)<<4|b>>2));break;case 3:g.push(String.fromCharCode((c&3)<<6|b))}c=b;f++}return g.join("")}};
String.prototype.format=function(){var a=arguments;return String(this).replace(RegExp("{([0-"+a.length+"])}","g"),function(d,b){return a[b]})};typeof constant=="undefined"&&(constant={});
var Login={ERROR_TIPS:"_error_tips",RETURN_CODE:"code",USERID_DM:"userid_dm",DOMAIN_DM:"domain_dm",LOGINTYPE_DM:"logintype_dm",USER_PWDTYPE:"user_pwdType",ADDRESS_SELECT:"address_select",REMEMBERUSER_DM:"rememberuser_dm",SSL:"ssl",REPLY_LOGIN:8,init:function(a,d,b,c){this.isProvince=a.isProvince;this.code=GC.getUrlParamValue(location.href,this.RETURN_CODE);this.oUsernumber=jQuery("#"+a.usernumber);this.oUserId=jQuery("#"+a.userid);this.oDomain=jQuery("#"+a.domain);this.oPassword=jQuery("#"+a.password);
this.oRemember=jQuery("#"+a.remember);this.oErrorTip=jQuery("#"+a.errorTip);this.oSsl=jQuery("#"+a.ssl);this.oReturnurl=jQuery("#"+a.returnurl);this.oAddrSel=jQuery("#"+a.addrsel);this.oForm=jQuery("#"+a.form);this.oPasswordType=jQuery("#"+a.passwordType);this.oAddrPop=jQuery(a.addrPop);this.func=c;this.jtUid=a.jtUid;this.jtCorpDomain=a.jtCorpDomain;this.isStandard=a.isStandard;this.realDomain=a.realDomain;this.oMobileNumber=jQuery("#"+a.mobileNumber);this.oModel=jQuery("#"+a.model);if(a.ym)this.oYm=
jQuery("#"+a.ym);this.oIsAdminLogin=jQuery("#userLogin")[0];this.oUserLogin=jQuery("#"+a.userLogin);this.oAdminLogin=jQuery("#"+a.adminLogin);this.oKeyLogin=jQuery("#"+a.keyLogin);this.oLoginType=jQuery("#"+a.loginType);this.reg=d;this.len=b;this.attrs={};var e=this;if(e.oReturnurl.val()=="")a=window.location.href,a.indexOf("?")>0&&(a=a.substring(0,a.indexOf("?"))),e.oReturnurl.val(a);e.attrs.panel=GC.getCookie("panel")||1;e.oForm.submit(function(){return e.validate()});if(this.isDomainMode()&&this.oYm.width()&&
(a=jQuery("#liUserNum"))&&a.width())a=a.width()-this.oYm.width()-50,a<=60&&(a=60),this.oUsernumber.width(a);e.bindEvent();e.tempDomains=domains||[];Login.initLoginPanner();Login.initData(e.code);Login.initEvent();Login.showError("",e.code)},isDomainMode:function(){return this.oYm&&this.oYm.length?!0:!1},setNameTip:function(){jQuery("#usernumber").val()==""?$("#mail_acotip").show():$("#mail_acotip").hide();jQuery("#password").val()==""?$("#mail_pswtip").show():$("#mail_pswtip").hide();jQuery("#KeyPassWordDiv").val()==
""?$("#ukey_pin").show():$("#ukey_pin").hide()},bindEvent:function(){var a=this;a.oForm.keypress(function(d){if(d.keyCode=="13"&&(a.oUsernumber.val()||a.oUserId.val())&&a.oPassword.val())a.attrs&&a.attrs.panel&&a.setCookie(),a.doSubmit()});setTimeout(function(){a.setNameTip()},1);$("#usernumber").keydown(function(){setTimeout(function(){a.setNameTip()},1)});$("#KeyPassWordDiv").keydown(function(){setTimeout(function(){a.setNameTip()},1)});$("#password").keydown(function(){setTimeout(function(){a.setNameTip()},
1)});this.isDomainMode()||$("#usernumber").keyup(function(d){a.tempDomains=[];var b=jQuery("#usernumber")[0].value.split("@"),c;b.length>1&&(c=b[1],c=c.replace(/\./g,"\\."));for(b=0;b<domains.length;b++)domains[b].match(RegExp("^"+c+"","g"))&&a.tempDomains.push(domains[b]);a.initLoginPanner();a.showPannel(d);jQuery("#pwdBox").addClass("loginIpt-focus");a.selectLiId=a.getSelectedLoginId();c=jQuery("#loginPannel")[0];b=0;c&&(b=jQuery(c.childNodes[0]).height(),b<22&&(b=21.111112594604492));var e=b*10;
if(d.keyCode==40){a.selectLiId++;if(a.selectLiId*b>=e)jQuery("#loginPannel")[0].scrollTop=(a.selectLiId+1)*b-e;a.selectLiId==a.tempDomains.length?(jQuery("#loginPannel")[0].scrollTop=0,jQuery("#loginPannel").children("li .loginSelected").removeClass("loginSelected"),a.selectLiId=0):jQuery("#loginPannel").children("li .loginSelected").removeClass("loginSelected");c.childNodes[a.selectLiId].className="loginSelected"}if(d.keyCode==38){a.selectLiId--;if(jQuery("#loginPannel")[0].scrollTop>=0)jQuery("#loginPannel")[0].scrollTop=
(a.selectLiId+1)*b-e;if(a.selectLiId==-1)a.selectLiId=a.tempDomains.length-1,jQuery("#loginPannel")[0].scrollTop=(a.selectLiId+1)*b-e;jQuery("#loginPannel").children("li .loginSelected").removeClass("loginSelected");c.childNodes[a.selectLiId].className="loginSelected"}d.keyCode=="13"&&setTimeout(function(){a.inputFinish()},10)});$("#password").focus(function(){a.hideLoginPannel();jQuery("#pwdBox").addClass("loginIpt-focus");jQuery("#userNumBox").removeClass("loginIpt-focus")});$("#usernumber").focus(function(){a.hideLoginPannel();
jQuery("#pwdBox").removeClass("loginIpt-focus");jQuery("#userNumBox").addClass("loginIpt-focus")});$("#liUserNum").click(function(d){a.isDomainMode()||(a.initLoginPanner(),a.showPannel(d),jQuery("#userNumBox").addClass("loginIpt-focus"),jQuery("#pwdBox").removeClass("loginIpt-focus"))});$("#LoginMode").mouseover(function(){var d=jQuery("#loginModePannel").children();d[0]&&power_mail!=!0&&jQuery(d[0]).hide();d[1]&&power_disk!=!0&&jQuery(d[1]).hide();d[2]&&power_contacts!=!0&&jQuery(d[2]).hide();d[3]&&
power_schedule!=!0&&jQuery(d[3]).hide();jQuery("#modePannel").removeClass("fake_slt_off");jQuery("#modePannel").addClass("fake_slt_on");jQuery("#userNumBox").removeClass("loginIpt-focus");jQuery("#pwdBox").removeClass("loginIpt-focus");d=$("#loginModePannel");if(d.length>0)d.show(),a.loginModePannel=d;power_mail!=!0&&power_disk!=!0&&power_contacts!=!0&&power_schedule!=!0&&d.hide();return!1});$("#LoginMode").mouseout(function(){jQuery("#modePannel").removeClass("fake_slt_on");jQuery("#modePannel").addClass("fake_slt_off");
jQuery("#modePannel").removeClass("fake_slt_on");a.loginModePannel.hide();return!1});$("#loginModePannel").click(function(d){if(d.target){jQuery("#showMode")[0].innerHTML=d.target.parentNode.innerHTML;var b=d.target.parentNode.getAttribute("rel");a.oModel.val(b)}a.loginModePannel.hide();d.stopPropagation?d.stopPropagation():d.cancelBubble=!0;return!1});$("body").click(function(){a.hideLoginPannel();a.loginModePannel&&a.loginModePannel.hide();jQuery("#modePannel").removeClass("fake_slt_on")})},getSelectedLoginId:function(){var a=
jQuery("#loginPannel").children("li .loginSelected")[0];return a&&a.childNodes[0]?a.childNodes[0].getAttribute("rel")-0:"-1"},hideLoginPannel:function(){this.loginPannel&&this.loginPannel.hide();jQuery("#loginPannel").children("li .loginSelected").removeClass("loginSelected")},initLoginPanner:function(){var a=this,d=jQuery("#loginPannel")[0];if(d)d.innerHTML="";var b=jQuery("#usernumber")[0].value;b.split("@").length>1&&(b=b.split("@")[0]);for(var c=a.tempDomains.length,e="",f=0;f<c;f++){var g=a.tempDomains[f];
e+=f==a.selectLiId?'<li class="loginSelected"><a rel='+f+' href="#">'+b+"@"+g+"</a></li>":"<li><a rel="+f+' href="#">'+b+"@"+g+"</a></li>"}if(d)d.innerHTML=e;jQuery("#loginPannel").click(function(b){if(b=(b.target||b.srcElement).getAttribute("rel")){var c=jQuery("#usernumber")[0].value;c.split("@").length>1&&(c=c.split("@")[0]);jQuery("#usernumber")[0].value=c+"@"+a.tempDomains[b]}a.hideLoginPannel()})},inputFinish:function(){var a=jQuery("#loginPannel").children(".loginSelected");if(a&&a[0]&&a[0].childNodes)jQuery("#usernumber")[0].value=
a[0].childNodes[0].innerHTML;this.hideLoginPannel()},isInputFinish:function(a){return a==""?!0:RegExp("(^|,)"+a+"(,|$)").test(domains)?!1:!0},showPannel:function(a){if(!this.isPhoneLogin){var d=jQuery("#loginPannel"),b=jQuery("#usernumber")[0].value,c,e=b.split("@");e.length>1&&(c=e[1]);if(d[0]&&b.match(/\@/ig)&&!b.match(/^\@/ig)&&b.match(/\@/ig).length==1&&this.isInputFinish(c))d.show(),this.loginPannel=d,d[0].style.height=22*this.tempDomains.length<212?22*this.tempDomains.length+"px":"212px";this.tempDomains.length<
1&&this.loginPannel&&this.loginPannel.hide();this.selectLiId=this.getSelectedLoginId();if((d=jQuery("#loginPannel")[0])&&d.childNodes.length>0)if(this.selectLiId=="-1")d.childNodes[0].className="loginSelected";else if(this.selectLiId>-1)d.childNodes[this.selectLiId].className="loginSelected"}a.stopPropagation?a.stopPropagation():a.cancelBubble=!0;a.preventDefault?a.preventDefault():a.returnValue=!1},initEvent:function(){var a=jQuery;if(this.code==="err_005"||this.code==="err_006")a("#li_verifyCode").show(),
a("#loginContainer").removeClass("login").addClass("login-verifyCode"),this.refreshImgRndCode(),this.inint_verifyEvent();a("#login_otp").unbind("click").bind("click",this.doSubmit)},inint_verifyEvent:function(){var a=jQuery;a("#mail_vctip").click(function(){a("#txtVerifyCode").focus()});a("#txtVerifyCode").unbind().bind("keyup",function(){a(this).val().replace(/^\s+/,"").replace(/\s+$/,"")==""?(a("#mail_vctip").show(),a(this).css("color","#bebebe")):(a("#mail_vctip").hide(),a(this).css("color","#000000"))})},
refreshImgRndCode:function(){jQuery("#imgRnd")[0].src=constant.imgUrl+"?r="+(new Date).getTime()},showAddressPop:function(){Login.oAddrPop.fadeIn("slow")},hideAddressPop:function(){Login.oAddrPop.fadeOut("slow")},setDomain:function(a){var d=a.id,a=$(a).text();this.oAddrSel.html(a+"<i></i>").attr("sd",d);a.length==3?this.oAddrSel.addClass("three-word"):this.oAddrSel.removeClass("three-word")},initData:function(a){function d(){var a=g.replace(/\./g,"\\.");$("#"+a).text()&&(a=$("#"+a).text(),b.oAddrSel.attr("sd",
g).html(a+"<i></i>"),a.length==3?b.oAddrSel.addClass("three-word"):b.oAddrSel.removeClass("three-word"))}var b=Login,c=GC.getCookie(b.USERID_DM),e=GC.getCookie(b.DOMAIN_DM)||"",f=GC.getCookie(b.REMEMBERUSER_DM),g=GC.getCookie(b.ADDRESS_SELECT),k=GC.getCookie(b.SSL),h=GC.getCookie(b.USER_PWDTYPE),j=GC.getCookie("panel");b.attrs.mail=GC.getCookie("mailAccount");b.attrs.phone=GC.getCookie("phoneAccount");if(f=="true")b.isDomainMode()?b.oUsernumber.val(c):b.isStandard&&c?e==""?b.oUsernumber.val(c):b.realDomain?
b.oUsernumber.val(c):b.oUsernumber.val(c+"@"+e):c&&b.isProvince?b.oUsernumber.val(c):c&&b.oUsernumber.val(c),b.oRemember.attr("checked",!0),k=="true"&&b.oSsl.attr("checked",!0),b.oAddrSel&&g&&d();else if(Login.realDomain)g=Login.realDomain,d();j&&j.toString()=="2"?(b.oUsernumber.val(b.attrs.phone),b.adminLogin()):j&&j.toString()=="1"&&(b.oUsernumber.val(b.attrs.mail),b.userLogin());j=="1"?b.oUsernumber.val(b.attrs.mail):j=="2"&&b.oUsernumber.val(b.attrs.phone);a?(b.isDomainMode()||(b.isStandard&&
c?e==""?b.oUsernumber.val(c):b.realDomain?b.oUsernumber.val(c):b.oUsernumber.val(c+"@"+e):c&&b.isProvince?b.oUsernumber.val(c):c&&(!b.isDomainMode()&&(!b.panel||"1"==b.panel)?b.oUsernumber.val(c+"@"+e):b.oUsernumber.val(c))),b.oAddrSel&&g&&d(),k=="true"&&b.oSsl.attr("checked",!0),h=="1"&&(TC.userDynamicPwd(),TC.oOtpTip.show().addClass("pb18"),TC.oPassword.removeAttr("disabled").focus().removeClass("log_txt_unable").addClass("log_txt").css({"box-shadow":"1px 2px 1px #E3E3E3 inset"}).parent("li").removeClass("pb18"),
TC.oLoginBtn.attr("href","javascript:doLogin();"),TC.oLoginText.text("\u767b\u5f55"))):b.oRemember.is(":checked")||b.oUsernumber.val("");a=[typeof power_mail!="undefined"?power_mail:!1,typeof power_disk!="undefined"?power_disk:!1,typeof power_contacts!="undefined"?power_contacts:!1,typeof power_schedule!="undefined"?power_schedule:!1];c=!1;for(e=0;e<a.length;e++)!c&&a[e]&&(f=jQuery("#loginModePannel li:eq("+e+")"),jQuery("#showMode").html(f.html()),f=f.attr("rel"),b.oModel.val(f),c=!c)},setCookie:function(){var a=
Login,d=window.webpath,b=new Date;b.setTime(b.getTime()+12096E5);GC.setCookie(a.USERID_DM,a.oUserId.val(),d,null,b);GC.setCookie(a.DOMAIN_DM,a.oDomain.val(),d,null,b);GC.setCookie(a.USER_PWDTYPE,a.oPasswordType.val(),d,null,b);a.attrs&&a.attrs.panel&&GC.setCookie("panel",a.attrs.panel,d,null,b);a.attrs.panel=="1"&&GC.setCookie("mailAccount",a.oUsernumber.val(),d,null,b);a.attrs.panel=="2"&&GC.setCookie("phoneAccount",a.oUsernumber.val(),d,null,b);a.oAddrSel&&GC.setCookie(a.ADDRESS_SELECT,a.oAddrSel.attr("sd"),
d,null,b);a.oRemember.is(":checked")?GC.setCookie(a.REMEMBERUSER_DM,"true",d,null,b):GC.setCookie(a.REMEMBERUSER_DM,"false",d,null,b);a.oSsl.is(":checked")?GC.setCookie(a.SSL,"true",d,null,b):GC.setCookie(a.SSL,"false",d,null,b);GC.setCookie("isFirstLogin","",d,null,b)},doSubmit:function(){var a=Login;a.oIsAdminLogin?a.oLoginType.val("WEB"):a.oLoginType.val("ADMIN");window.top.isEncryptPwd=="1"?RSAKey&&RSAKey.getPublicKey(function(d){window.top.publicKey=d;a.oForm.submit()},!0):a.oForm.submit()},
validate:function(){var a=Login,d=jQuery.trim(a.oUsernumber.val()),b=window.defaultDomain||"";!a.isPhoneLogin&&d.indexOf("@")==-1&&b&&(d+="@"+b);a.oErrorTip.hide();if(a.isStandard)if(a.realDomain&&a.realDomain.length>0)a.oUserId.val(d||"");else{if(b=d.split("@"))a.oUserId.val(jQuery.trim(b[0])||""),a.oDomain.val(jQuery.trim(b[1])||a.oAddrSel.attr("sd")||"")}else if(a.isProvince)a.oUserId.val(d||"");else if(d){if(b=d.split("@"))a.oUserId.val(jQuery.trim(b[0])||""),!b[1]&&a.oDomain?a.oDomain.val(a.realDomain):
a.oDomain.val(jQuery.trim(b[1])||a.oAddrSel.attr("sd")||"")}else a.oUserId.val(""),a.oDomain.val("");var c=a.oUserId.val(),e=a.oDomain.val(),f=a.oPassword.val();a.realDomain&&a.oDomain.val(a.realDomain);var g=b="",k="",h=!0,j=a.len,l=jQuery;c.length==0?(b="err_003",h=!1):c.length>j.userid_max?(b="err_004",g=j.userid_max,h=!1):c.match(a.reg.userid)||(b="err_004",h=!1);k="userid";if(h&&!a.isPhoneLogin)e.length==0?(b="err_009",h=!1):e.length>j.domain_max?(b="err_010",g=j.domain_max,h=!1):e.match(a.reg.domain)||
(b="err_010",h=!1),k="domain";a.oMobileNumber.val(d||"");a.isPhoneLogin&&!d.match(a.reg.mobile)&&(b="err_009",h=!1);if(h&&Login.REPLY_LOGIN!=a.oPasswordType.val()){if(f.length==0)b="err_013",h=!1;else if(f.length>j.password_max)b="err_004",h=!1,g=j.password_max;else if(f.length<j.password_min)b="err_004",g=j.password_min,h=!1;k="password"}return h&&!l("#li_verifyCode").is(":hidden")&&(d=l("#txtVerifyCode").val(),d!=void 0&&d.replace(/^\s+|\s+$/,"")=="")?(l("#errorTips").show().html("\u8bf7\u8f93\u5165\u56fe\u7247\u9a8c\u8bc1\u7801"),
!1):h?(a.setCookie(),RSAKey&&(window.top.cfgAuthMd5=="1"||window.top.isEncryptPwd=="1"&&window.top.publicKey)&&a.oPassword.val(RSAKey.encrypt(a.oPassword.val(),window.top.publicKey)),!0):(a.showError(k,b,g),!1)},showError:function(a,d,b){var c=Login.func,e=LEM.getErrorMsg(d,GC.getCookie("lang"+Login.sid));e&&(e=e.format(b),typeof c=="function"?c(a,d,e):d?(Login.oErrorTip.text(e).show(),GC.getCookie(Login.USER_PWDTYPE)=="1"&&(TC.userDynamicPwd(),Login.oPassword.removeAttr("disabled").focus())):Login.oErrorTip.hide())},
userLogin:function(){
	var a=Login;a.setUserLoginDisplay();
	$("#login_otp").unbind("click").bind("click",a.doSubmit);
	if(a.attrs&&a.attrs.panel){
	var d=a.oUsernumber.val();a.attrs.tempMail=d}a.setFocus();
	a.oKeyLogin.removeClass("on");
	a.oAdminLogin.removeClass("on");
	a.oUserLogin.addClass("on");
	a.oIsAdminLogin?a.oLoginType.val("WEB"):a.oLoginType.val("ADMIN");
	a.isPhoneLogin=!1;

	jQuery("#mail_acotip")[0].innerHTML="\u90ae\u7bb1\u5e10\u53f7";
	jQuery("#userNumBox").addClass("loginIpt-focus");
	jQuery("#liCodeBox").hide();
	jQuery("#pwdBox").show().removeClass("loginIpt-focus");
	jQuery("#userLoginIco").removeClass("i-phone").addClass("i-uid");
	
	
	
	a.isDomainMode()&&a.oYm.show();
	a.attrs.panel=1;
	a.attrs&&a.attrs.mail&&GC.getCookie(a.REMEMBERUSER_DM)=="true"?a.oUsernumber.val(a.attrs.mail):a.oUsernumber.val("");
	setTimeout(function(){a.setNameTip()},1);
	
	
	a.oPassword.val("")},adminLogin:function(){
	var a=Login;
	if(a.attrs&&a.attrs.panel){
	var d=a.oUsernumber.val();
	a.attrs.tempPhone=d}a.oUserLogin.removeClass("on");
	a.oAdminLogin.addClass("on");
	a.setFocus();
	
	a.oIsAdminLogin?a.oLoginType.val("WEB"):
	a.oLoginType.val("ADMIN");a.isPhoneLogin=!0;jQuery("#mail_acotip")[0].innerHTML="\u624b\u673a\u53f7\u7801";
	jQuery("#userNumBox").addClass("loginIpt-focus");
	//jQuery("#pwdBox").removeClass("loginIpt-focus");
	jQuery("#pwdBox").removeClass("loginIpt-focus").hide();
	jQuery("#liCodeBox").show();
	jQuery("#userLoginIco").removeClass("i-uid").addClass("i-phone");
	a.isDomainMode()&&a.oYm.hide();a.attrs.panel=2;


a.attrs&&a.attrs.phone&&GC.getCookie(a.REMEMBERUSER_DM)=="true"?a.oUsernumber.val(a.attrs.phone):a.oUsernumber.val("");setTimeout(function(){a.setNameTip()},1);a.oPassword.val("")},setFocus:function(){var a=
Login;a.oUsernumber.val()?a.oPassword.focus():a.oUsernumber.focus()},setUserLoginDisplay:function(){$("#liUserNum, #liPassword, #liRemeberUser").show();$("#divIEAlertText,#divcePannel, #DevicelistDivId, #SelectUSBDivId, #liUkey").hide();$("#errorTips").text("")},setKeyLoginDisplay:function(){var a=Login;$("#liUserNum, #liPassword, #liRemeberUser, #selectUSBUl").hide();a.oKeyLogin.addClass("on");a.oUserLogin.removeClass("on");$("document").bind("click",function(){$("#DevicelistDivId").hide();$("#selectUSBUl").hide()});
$("#errorTips").text("")},getChallenge:function(a){var d=this.webPath+"/service/mail/ibc.do?func=mail:GenChallenge";a&&(d=this.webPath+"/service/ibc.do?func=ibc:GenChallenge");$.ajax({type:"POST",url:d,data:{},dataType:"json",success:function(a){a=a?a["var"]||"":"";$("#chapchallenge").val(a)},error:function(){$("#errorTips").text("\u83b7\u53d6\u6311\u6218\u503c\u5931\u8d25").show()}})},keyLogin:function(a){var d=Login;d.webPath=typeof gMain!=="undefined"?gMain.webPath||"":"";d.resourcePath=typeof gMain!==
"undefined"?gMain.resourcePath||"":"";$("#login_otp").unbind("click");$("#KeyPassWordDiv").val("");d.setKeyLoginDisplay();typeof CreateKeyLoginWindows==="function"&&(CreateKeyLoginWindows("login_ul"),$("#downUsbDriver").unbind().bind("click",function(){location.href=d.resourcePath+"/login/download/ThinkMail_IBCSecuity.exe"}),d.getChallenge(a));if(d.attrs&&d.attrs.panel)a=d.oUsernumber.val(),d.attrs.tempPhone=a;d.oLoginType.val("KEY");d.isKeyLogin=!0}},LEM={DEFAULT_CODE:"err_029",DEFAULT_LANG:"zh_CN",
getErrorMsg:function(a,d){var d=d||this.DEFAULT_LANG,b=this["ERRORMSG_"+d],b=b||this.ERRORMSG_zh_CN,c=b[a];return c?c:b[this.DEFAULT_CODE]},ERRORMSG_zh_CN:{err_001:"\u90ae\u7bb1\u5730\u5740\u8f93\u5165\u9519\u8bef",err_002:"\u8bf7\u8f93\u5165\u90ae\u7bb1\u8d26\u53f7",err_003:"\u8bf7\u8f93\u5165\u60a8\u7684\u7528\u6237\u540d",err_004:"\u7528\u6237\u540d\u6216\u5bc6\u7801\u9519\u8bef",err_005:"\u767b\u5f55\u6b21\u6570\u8fc7\u4e8e\u9891\u7e41\uff0c\u4e3a\u4fdd\u969c\u5b89\u5168\uff0c\u8bf7\u8f93\u5165\u56fe\u7247\u9a8c\u8bc1\u7801",
err_006:"\u9a8c\u8bc1\u7801\u9519\u8bef\uff0c\u8bf7\u91cd\u65b0\u8f93\u5165",err_007:"\u5bf9\u4e0d\u8d77\uff0c\u60a8\u6ca1\u6709\u767b\u5f55\u6743\u9650",err_009:"\u8bf7\u8f93\u5165\u6b63\u786e\u7684\u4f01\u4e1a\u90ae\u7bb1\u5e10\u53f7",err_010:"\u57df\u540d\u8f93\u5165\u9519\u8bef",err_011:"\u57df\u540d\u4e0d\u5b58\u5728\u6216\u8be5\u57df\u540d\u5df2\u8fc7\u671f!",err_013:"\u8bf7\u8f93\u5165\u60a8\u7684\u5bc6\u7801",err_014:"\u8bc1\u4e66\u4e0d\u5408\u6cd5",err_028:"\u7528\u6237\u767b\u5f55\u5931\u8d25,\u8bf7\u4e0e\u7cfb\u7edf\u7ba1\u7406\u5458\u8054\u7cfb!",
err_029:"\u7528\u6237\u767b\u5f55\u5931\u8d25,\u8bf7\u4e0e\u7cfb\u7edf\u7ba1\u7406\u5458\u8054\u7cfb!",err_101:"\u767b\u5f55\u72b6\u6001\u5df2\u5931\u6548\uff0c\u8bf7\u91cd\u65b0\u767b\u5f55!",err_012:"IP\u5730\u5740\u8fdb\u5165\u9ed1\u540d\u5355",err_030:"MAC\u9650\u5236",err_031:"IP\u9650\u5236",err_032:"\u7f51\u7edc\u9650\u5236",err_cancel_004:"\u6b64\u57df\u540d\u4e0d\u5b58\u5728",err_lock_004:"\u6b64\u8d26\u53f7\u5df2\u88ab\u6ce8\u9500",err_notfound_004:"\u6b64\u5e10\u53f7\u4e0d\u5b58\u5728"}};
$(document).ready(function(){function a(){var a=$(".con"),b=($(window).height()-450)/2;b-=60;b<0&&(b=0);a.css("margin-top",b+"px");$("#header").css("margin-top",b+"px")}$(".log_tab a").click(function(){var a=$(".log_tab a").index(this)==1?"ADMIN":"WEB";$("#loginType").val(a);$(this).removeClass("current").siblings().addClass("current")});var d=$("#usernumber"),b=$("#password");$("#mail_acotip").click(function(){d.focus()});a();$(window).resize(a);$("#mail_pswtip").click(function(){b.focus()});$("#ukey_pin").live("click",
function(){$("#KeyPassWordDiv").focus()});setTimeout(function(){if(d.val()){var a=b.value;b.focus();b.value="";b.value=a}else d.focus()},300);var c,e;$("#staticPwd").hover(function(){c=setTimeout(TC.userStaticPwd,1)},function(){clearTimeout(c)});$("#dynamicPwd").hover(function(){e=setTimeout(TC.userDynamicPwd,1)},function(){clearTimeout(e)});var f,g;if(jQuery("#userLogin")[0]&&(typeof isShowMobile=="undefined"||isShowMobile!="0"))$("#adminLogin").hover(function(){f=setTimeout(Login.adminLogin,800)},
function(){clearTimeout(f)}),$("#userLogin").hover(function(){g=setTimeout(Login.userLogin,800)},function(){clearTimeout(g)});var k;$("#address-select, .dropdown").hover(function(){k=setTimeout(Login.showAddressPop,800)},function(a){a=a.relatedTarget.className;a!="address-ul clearfix addr"&&a!="address-pop"&&a!="dropdown"&&Login.hideAddressPop();clearTimeout(k)});$(".address-pop").mouseout(function(a){a=a.relatedTarget.className;a!="addr"&&a!="address-ul clearfix addr"&&Login.hideAddressPop()});var h=
$.browser;window.skinControl==1&&h.msie&&h.version<9&&($("#login_div,.login-tabs").css("filter",""),$("#login_div").css("background","#fff"),$(".login-tabs").children().length==1&&$(".login-tabs").attr("style","filter:'';background:#fff"),$(".login-tabs a").css({color:"#0033CC",filter:"",background:"#fff"}))});
(function(){function a(){var a=c(),b=$("#login_form")[0];if(a=="")return!1;document.getElementById("responseData").value=a;b.method="post";b.action=o+"/login/loginibc.do";b.submit()}function d(){try{return"undefined"!=typeof myibc.myibc.factory?!0:!1}catch(a){return!1}}function b(){var a=navigator.userAgent.toLowerCase().search(/(msie\s|trident.*rv:)([\w.]+)/)!=-1;if($.browser.msie||a){if(window.myibc&&myibc.myibc)return 1;try{var b=document.getElementById("Calc"),c=b.GetSecurityEngine();if(c==1){factory=
b;var d=b.GetVersion();window.myibc||(myibc={});if(!myibc.myibc)myibc.myibc={factory:b,info:d};return 1}else $("#errorTips").show().text(b.GetErrMsg(c))}catch(e){$("#errorTips").show().text(n)}}return!1}function c(){var a=$("#showDivce").attr("value"),b=$("#showUsb").attr("value"),c="",d=$("#KeyPassWordDiv").val(),a=parseInt(a,10);if(b==1)return $("#errorTips").text("\u8bf7\u9009\u62e9\u79c1\u94a5\u6807\u8bc6").show(),"";if(d=="")return $("#errorTips").show().text("UKEY PIN\u7801\u4e0d\u80fd\u4e3a\u7a7a"),
"";else if(d.length<4||d.length>=15)return $("#errorTips").show().text("UKEY PIN\u7801\u957f\u5ea6\u4e0d\u80fd\u5c0f\u4e8e4\u4f4d\u6216\u8005\u5927\u4e8e14\u4f4d"),"";else{challengeData=$("#"+p).val();if(challengeData.length!=32)return $("#errorTips").show().text("\u83b7\u53d6\u6311\u6218\u503c\u9519\u8bef,\u8bf7\u5237\u65b0\u9875\u9762"),!1;l=myibc.myibc.factory;if("undefined"==typeof l)return $("#errorTips").show().text(n),"";var e;try{if(e=l.LoginDevice(a,b,d),e==1?challengeData!=""&&(c=l.LoginWithChap(challengeData)):
$("#errorTips").show().text(l.GetErrMsg(e)),"undefined"==typeof c)return $("#errorTips").show().text("\u7b7e\u540d\u5931\u8d25\uff01"),""}catch(f){return""}}return c}function e(){if(d()){l=myibc.myibc.factory;"undefined"==typeof l&&$("#errorTips").show().text(n);try{l.SetCallBack(f),h()?($("#"+m).val(""),j()):($("#errorTips").show().text("\u8bf7\u9009\u62e9\u79c1\u94a5\u6807\u8bc6"),$("#"+m).val(""))}catch(a){$("#errorTips").show().text("")}}else $("#divIEAlertText").show()}function f(a,b){l=myibc.myibc.factory;
$("#errorTips").text("");$("#KeyPassWordDiv").val("");b==1?(k(),g(),j()):h()?$("#"+m).val(""):(k(),g(),$("#"+m).val(""),j())}function g(){$("#selectUSBUl").html("");$("#showUsb").text("\u8bf7\u9009\u62e9\u79c1\u94a5\u6807\u8bc6")}function k(){$("#DevicelistDivId").html("");$("#showDivce").text("\u8bf7\u9009\u62e9\u5bc6\u7801\u8bbe\u5907")}function h(){try{var a=l.GetDeviceInfo();return"undefined"!=typeof a?"0;;0;"==a?!1:myibc.myibc.info=a:!1}catch(b){return!1}}function j(){var a=myibc.myibc.factory,
b=a.GetDeviceInfo();if("undefined"==typeof a)$("#errorTips").show().text(n);else{k();try{if("undefined"!=typeof b){var c=b.split(";"),d=c[0];if(d==4){for(var e=parseInt(c[2]),d="",f=1;f<=e;f++)d='<li rel="" value="'+c[2+f]+'"><a style="display:block;"  href="javascript:;">'+c[2+f]+"</a></li>";$("#DevicelistDivId").append(d)}else{e=1;for(f=0;f<d;f++){var g='<li rel="" value="'+d+'"><a style="display:block;"  href="javascript:;">'+c[e]+"</a></li>";$("#DevicelistDivId").append($(g));e++;var h=c[e];h++;
e+=parseInt(h)}}$("#DevicelistDivId").find("li").eq(0).click();$("#DevicelistDivId").hide()}}catch(l){a.GetErrMsg(b)!=""&&$("#errorTips").show().text(a.GetErrMsg(b))}}}var l,n="\u8bf7\u4e0b\u8f7d\u5b89\u88c5USB\u5b89\u5168\u63a7\u4ef6",p="chapchallenge",m="KeyPassWord",o="";window.CreateKeyLoginWindows=function(c){c=document.getElementById(c);o=gMain?gMain.webPath||"":"";if(null==c)return!1;if("undefined"===typeof $("#"+p).val())return!1;$("#DevicelistDivId").delegate("li","click",function(){$("#showDivce").text($(this).find("a").text());
$("#showDivce").attr("value",$(this).attr("value"));$("#selectUSBUl").hide();l=myibc.myibc.factory;if("undefined"==typeof l)$("#errorTips").show().text(n);else{var a=$("#showDivce").attr("value"),b=$("#showDivce").text(),c=l.GetDeviceInfo(),d=c.split(";"+b+";");g();try{if("undefined"!=typeof c.split(";")){var e=0,f=0;do f=c.indexOf(b,f),f!=-1&&(e++,f+=b.length);while(f!=-1);if(e>1){if(c.indexOf("\u6587\u4ef6\u79c1\u94a5")==-1)var h=d[a].split(";"),j=h[0];else h=d[a-1].split(";"),j=h[0];for(var k=
0;k<j;k++){var m='<li rel="" value="'+h[k+1]+'"><a style="display:block;"  href="javascript:;">'+h[k+1]+"</a></li>";$("#selectUSBUl").append($(m))}}else{h=d[1].split(";");j=h[0];for(k=0;k<j;k++)m='<li rel="" value="'+h[k+1]+'"><a style="display:block;"  href="javascript:;">'+h[k+1]+"</a></li>",$("#selectUSBUl").append($(m))}$("#selectUSBUl").find("li").eq(0).click();$("#selectUSBUl").hide()}}catch(o){l.GetErrMsg(c)!=""&&$("#errorTips").show().text(l.GetErrMsg(c))}}});$("#divcePannel").unbind().bind("click",
function(a){d()?h()||$("#errorTips").show().text("\u8bf7\u63a5\u5165key\u76d8"):$("#errorTips").show().text(n);$("#DevicelistDivId")[0].style.display==="none"?$("#DevicelistDivId").show():$("#DevicelistDivId").hide();a.stopPropagation();return!1});$(document).bind("click",function(){$("#DevicelistDivId").hide()});$("#SelectUSBDivId").unbind().bind("click",function(a){d()?h()||$("#errorTips").show().text("\u8bf7\u63a5\u5165key\u76d8"):$("#errorTips").show().text(n);$("#selectUSBUl")[0].style.display===
"none"?$("#selectUSBUl").show():$("#selectUSBUl").hide();a.stopPropagation();return!1});$("#selectUSBUl").delegate("li","click",function(){var a=$(this).find("a").text();$("#showUsb").text(a);$("#showUsb").attr("value",a)});$(document).bind("click",function(){$("#selectUSBUl").hide()});checkDiv=$("#divIEAlert").val();typeof checkDiv=="undefined"&&($("#divIEAlertText")[0]||c.appendChild($('<li  id="divIEAlertText"></li>')[0]));$("#login_otp").bind("click",a);$("#divIEAlertText").html("loading...").show().slideDown("fast");
b();$("#liUkey").show();e();if($.browser.opera)return $("#errorTips").text("\u5b89\u5168\u63a7\u4ef6\u4e0d\u652f\u6301Opera\u6d4f\u89c8\u5668,\u8bf7\u4f7f\u7528IE\u6d4f\u89c8\u5668").show(),$("#divIEAlertText").hide(),$("#SelectUSBDivId").unbind(),$("#divcePannel").unbind(),$("#login_otp").unbind(),!1;else if($.browser.mozilla&&document.documentMode!=10&&document.documentMode!=11)return $("#errorTips").text("\u5b89\u5168\u63a7\u4ef6\u4e0d\u652f\u6301firefox,\u8bf7\u5b89\u88c5IE Tab\u63d2\u4ef6!").show(),
$("#divIEAlertText").hide(),$("#SelectUSBDivId").unbind(),$("#divcePannel").unbind(),$("#login_otp").unbind(),!1;else if($.browser.safari)return $("#errorTips").text("\u5b89\u5168\u63a7\u4ef6\u4e0d\u652f\u6301Safari\u6d4f\u89c8\u5668,\u8bf7\u4f7f\u7528IE\u6d4f\u89c8\u5668").show(),$("#divIEAlertText").hide(),$("#SelectUSBDivId").unbind(),$("#divcePannel").unbind(),$("#login_otp").unbind(),!1;else d()?$("#divIEAlertText").hide():$("#divIEAlertText").html('\u60a8\u7684\u7535\u8111\u672a\u5b89\u88c5USB-key\u9a71\u52a8<br/>\u8bf7<a id="downUsbDriver" href="###">\u4e0b\u8f7dUSB-key\u9a71\u52a8</a>\uff0c\u5b89\u88c5\u540e\u8bf7\u5237\u65b0\u6216\u91cd\u542f\u6d4f\u89c8\u5668\u3002').show();
$("#liUkey").show();e()}})();typeof constant=="undefined"&&(constant={});
(function(a){var d={init:function(){var b=this;b.getWay="";a("#mailIndex,#mailCancel").unbind().bind("click",function(){b.comm.goLogin();return!1});a("#vdCode").unbind().bind("click",function(b){var e=d;e.comm.hideAll();a("#vdEmail").show();e.comm.resetProperty();e.getWay="phoneBind";a("#getWayTip").html("\u624b\u673a\u77ed\u4fe1\u9a8c\u8bc1");e.initEmailEvent();b.stopPropagation();return!1});b.comm.hideAll();a("#choiseWay").show();a("#vdSq").unbind().bind("click",function(b){var e=d;e.comm.hideAll();
a("#vdEmail").show();e.comm.refreshImgRndCode();e.comm.resetProperty();e.getWay="safeQuestion";a("#getWayTip").html("\u5b89\u5168\u95ee\u9898\u9a8c\u8bc1");e.initEmailEvent();b.stopPropagation();return!1})},initEmailEvent:function(){var b=this;b.resetValue();a("#mailAccount").focus();a("#picCodeTip,#mailAccountTip").hide();a("#mail_back").unbind().bind("click",function(){a("#choiseWay").show();a("#vdEmail").hide();return!1});a("#mail_nextStep").unbind().bind("click",function(a){if(b.checkMailAccount())return b.ajaxMail(),
!1;a.stopPropagation()});a("#mailAccount,#picCode").unbind().bind("keyup",function(a){if(a.which==13&&b.checkMailAccount())return b.ajaxMail(),!1});a("#imgRnd,#changeImg").unbind().bind("click",function(a){b.comm.refreshImgRndCode();a.stopPropagation();return!1})},checkMailAccount:function(){var b="",c="",c="safeQuestion"==this.getWay?"picCode_answer":"picCode",b=a("#mailAccount").val(),c=a("#"+c).val();this.mailAccount=b;this.picCode=c;a("#mailAccountTip,#picCodeTip").hide();if(this.comm.checkEmpty(b))return a("#mailAccountTip").html("\u90ae\u7bb1\u8d26\u53f7\u4e0d\u80fd\u4e3a\u7a7a").show(),
!1;return!this.comm.checkData("email",a("#mailAccount").val())?(a("#mailAccountTip").html("\u8bf7\u8f93\u5165\u6b63\u786e\u7684\u90ae\u7bb1").show(),!1):!0},ajaxMail:function(){var b=this,c={},b=this,d="",c="",c=c=null,c={email:b.mailAccount};if(b.getWay==="phoneBind")c.isPhone=!0,b.isPhone=!0,a("#getWayTip").html("\u624b\u673a\u77ed\u4fe1\u9a8c\u8bc1");else if(b.getWay==="safeQuestion")b.isQuestion=!0,c.isPhone=!1,a("#getWayTip").html("\u5b89\u5168\u95ee\u9898\u9a8c\u8bc1");d=b.comm.url.webPath+
"/service/common/validate.do?func="+b.comm.func.ValidateUserCode;b.comm.doService({type:"POST",url:d,data:c,fnSuc:function(c){c||b.getFailTip();var d=c.code,c=c["var"];if(d==="S_OK")b.isPhone&&c?(b.mobilePhone=c,a("#vdEmail").hide(),a("#vdPhone").show(),b.initVdCodeEvent()):b.isQuestion&&c?(b.safeQuestion=c,a("#vdEmail").hide(),a("#vdQuestion").show(),b.initVdAnswerEvent()):b.getFailTip();else{switch(d.toUpperCase()){case "USER_NOT_FOUND":a("#mailAccountTip").html("\u90ae\u7bb1\u4e0d\u5b58\u5728\uff0c\u8bf7\u91cd\u65b0\u8f93\u5165").show();
break;case "QUESTION_NOT_EXIST":a("#emailCode").hide();a("#vdAll,#vdSafeQuestion").show();b.comm.alert("\u672a\u7ed1\u5b9a\u5bc6\u7801\u5b89\u5168\u95ee\u9898\uff0c\u8bf7\u8054\u7cfb\u7ba1\u7406\u5458\u91cd\u7f6e\u5bc6\u7801");break;case "MOBILEPHONE_NOT_EXIST":b.comm.alert("\u672a\u5f00\u901a\u624b\u673a\u77ed\u4fe1\u9a8c\u8bc1\u7801\u670d\u52a1\uff0c\u8bf7\u8054\u7cfb\u7ba1\u7406\u5458\u91cd\u7f6e\u5bc6\u7801");break;default:b.comm.alert("\u64cd\u4f5c\u5931\u8d25")}a("#mailAccount").blur()}},dataType:"json",
fnFail:function(){b.getFailTip()}});b.comm.refreshImgRndCode()},getFailTip:function(){this.isPhone?this.comm.alert("\u83b7\u53d6\u7ed1\u5b9a\u624b\u673a\u53f7\u5931\u8d25"):this.comm.alert("\u83b7\u53d6\u5bc6\u7801\u5b89\u5168\u95ee\u9898\u5931\u8d25")},initVdAnswerEvent:function(){function b(a){function b(){if(a){if(a==13&&c.checkAnswer())return c.ajaxAnswer(),!1}else if(c.checkAnswer())return c.ajaxAnswer(),!1}window.top.isEncryptPwd=="1"?RSAKey&&RSAKey.getPublicKey(function(a){window.top.publicKey=
a;b()},!0):b()}var c=this;c.resetValue();a("#safeCancel").unbind().bind("click",function(b){a("#vdEmail").show();c.comm.refreshImgRndCode();a("#vdQuestion").hide();b.stopPropagation();return!1});a("#safeOk").unbind().bind("click",function(a){b();a.stopPropagation();return!1});a("#imgAnswer,#changeImg").unbind().bind("click",function(a){c.comm.refreshImgRndCode("imgAnswer");a.stopPropagation();return!1});c.comm.refreshImgRndCode("imgAnswer");a("#txtAnswer").val("").focus();a("#txtSafe").html(c.safeQuestion);
a("#txtAnswer").unbind().bind("keyup",function(a){b(a.which);a.stopPropagation();return!1})},checkAnswer:function(){var b=a("#answerTip"),c=a("#txtAnswer").val(),d="safeQuestion"==this.getWay?"picCode_answer":"picCode";this.answer=this.comm.encodeHTML(c);this.picCode=a("#"+d).val();b.hide();return this.comm.checkEmpty(c)?(b.html("\u7b54\u6848\u4e0d\u80fd\u4e3a\u7a7a").show(),!1):!0},ajaxAnswer:function(){var b=this,c="";if(RSAKey&&(window.top.cfgAuthMd5=="1"||window.top.isEncryptPwd=="1"&&window.top.publicKey))b.answer=
RSAKey.encrypt(b.answer,window.top.publicKey);c={email:b.mailAccount,question:b.safeQuestion,answer:b.answer,code:b.picCode};url=b.comm.url.webPath+"/service/common/validate.do?func="+b.comm.func.ValidateUserQuestion;b.comm.doService({type:"POST",url:url,data:c,fnSuc:function(c){c||b.getFailTip();c=c.code;if(c==="S_OK")a("#vdQuestion").hide(),a("#setNewPassword").show(),b.initSetPassword();else switch(b.comm.refreshImgRndCode("imgAnswer"),c.toUpperCase()){case "VALIDATE_ERROR":a("#answerTip").html("\u7b54\u6848\u9519\u8bef\uff0c\u8bf7\u91cd\u65b0\u8f93\u5165").show();
break;default:a("#answerTip").html("\u9a8c\u8bc1\u5931\u8d25").show()}},dataType:"json",fnFail:function(){b.getFailTip()}})},resetValue:function(){a("#password,#comfirmPassword,#txtAnswer,#picCode,#text,#mailAccount").val("")},toggleGetCode:function(b){a(b).val().trim()==""?this.getcodeDisabled():this.getcodeAbled()},getcodeAbled:function(){a("#getCode").attr("class",this.comm.className.codeNormal);this.initGetCode()},getcodeDisabled:function(){a("#getCode").attr("class",this.comm.className.codeGray);
a("#getCode").unbind("click").bind("click",function(a){a.stopPropagation();return!1})},initVdCodeEvent:function(){function b(){a("#msCodeTip").hide();a("#getCodeTip").hide();c.code=a("#msCode").val();if(c.comm.checkEmpty(c.code))a("#msCodeTip").html("\u9a8c\u8bc1\u7801\u4e0d\u80fd\u4e3a\u7a7a").show(),a("#picCode").val().trim()==""&&c.getcodeDisabled();else return c.ajaxCheckCode(),!1}var c=this,d=c.mobilePhone||"";a("#picCode").focus();a("#getCode").html("\u83b7\u53d6\u77ed\u4fe1\u9a8c\u8bc1\u7801");
c.resetValue();a("#phoneCancel").unbind().bind("click",function(){a("#choiseWay").show();a("#vdPhone").hide();c.clearCodeInterval();c.vdpwd=null;return!1});a("#picCodeTip,#msCodeTip,#getCodeTip").hide();d=d.toString();a("#txtPhone").html(d);c.initGetCode();a("#phoneOk").unbind().bind("click",function(a){b();a.stopPropagation();return!1});a("#msCode").unbind().bind("keyup",function(a){if(a.which==13)return b(),!1});c.getcodeDisabled();a("#picCode").unbind().bind("keyup",function(){c.toggleGetCode(this)})},
goSetPass:function(){a("#vdPhone").hide();a("#setNewPassword").show();this.initSetPassword()},ajaxCheckCode:function(){var b=this,c={},b=this,d="",c="",c=a("#msCode").val();fnSuc=null;fnFail=null;b.vc=c;a("#msCodeTip").hide();fnSuc=function(c){c||b.getFailTip();if(c.code==="S_OK")b.goSetPass();else switch(c.code.toUpperCase()){case "VALIDATECODEISEXPIRED":a("#msCodeTip").html("\u9a8c\u8bc1\u7801\u8fc7\u671f,\u8bf7\u91cd\u65b0\u83b7\u53d6\u9a8c\u8bc1\u7801").show();break;case "VALIDATECODEISINVALID":a("#msCodeTip").html("\u65e0\u6548\u9a8c\u8bc1\u7801,\u8bf7\u91cd\u65b0\u8f93\u5165").show();
break;case "CODE_OVER_MAX_ERROR":a("#msCodeTip").html("\u9a8c\u8bc1\u7801\u9519\u8bef\u6b21\u6570\u8fc7\u591a\uff0c\u8bf7\u7a0d\u540e\u83b7\u53d6").show();break;default:a("#msCodeTip").html("\u9a8c\u8bc1\u5931\u8d25").show()}};c={mobilePhone:b.mobilePhone,validateCode:b.vc};fnFail=function(){b.initGetCode();b.getFailTip()};d=b.comm.url.webPath+"/service/common/validate.do?func="+b.comm.func.ValidateMobileCode;b.comm.doService({type:"POST",url:d,data:c,fnSuc:fnSuc,dataType:"json",fnFail:fnFail})},
initSetPassword:function(){var b=this;a("#newPassword").focus();b.resetValue();a("#cancelPass").unbind().bind("click",function(){b.comm.hideAll();a("#choiseWay").show();return!1});a("#savePass").unbind().bind("click",function(a){if(b.checkPass())return window.top.isEncryptPwd=="1"?RSAKey&&RSAKey.getPublicKey(function(a){window.top.publicKey=a;b.ajaxSetPass()},!0):b.ajaxSetPass(),!1;a.stopPropagation()});a("#newPassword,#comfirmPassword").unbind().bind("keyup",function(c){c=c.which;a("#newPasswordTip").hide();
a("#comfirmPasswordTip").hide();if(c==13&&b.checkPass())return window.top.isEncryptPwd=="1"?RSAKey&&RSAKey.getPublicKey(function(a){window.top.publicKey=a;b.ajaxSetPass()},!0):b.ajaxSetPass(),!1});a("#secGrade")[0]&&a("#secGrade").remove();var c={pwdId:"newPassword",NotContains:{Account:"",Mobile:"",Alias:""},sLevel:parseInt(constant.pwdCheckType,10)||1,pwdMaxLen:~~constant.pwdMaxLen||30,pwdMinLen:~~constant.pwdMinLen||6,wrapClassName:"pl155",wrapTagName:"div",contId:"checkPassStrengthTip"};a("#checkPassStrengthTip").length<
1&&a('<span class="red fz_12" id="checkPassStrengthTip"></span>').insertAfter("#newPasswordTip");b.vdpwd=new VdPassWord(c);a("#strPassLen").html((~~constant.pwdMinLen||6)+"-"+(~~constant.pwdMaxLen||20))},initGetCode:function(){var b=this;a("#getCode").unbind().bind("click",function(a){b.getCode();a.stopPropagation();return!1})},ajaxSetPass:function(){var b=this,c="";a("#newPasswordTip").hide();a("#comfirmPasswordTip").hide();a("#checkPassStrengthTip").hide();if(RSAKey&&(window.top.cfgAuthMd5=="1"||
window.top.isEncryptPwd=="1"&&window.top.publicKey))b.password=RSAKey.encrypt(b.password,window.top.publicKey);c={password:b.password};url=b.comm.url.webPath+"/service/common/validate.do?func="+b.comm.func.UpdateUserPassword;b.comm.doService({type:"POST",url:url,data:c,fnSuc:function(c){c||b.getFailTip();c=c.code;if(c==="S_OK")b.goPassSuc();else switch(c.toUpperCase()){case "WEAK_PWD":a("#newPasswordTip").html("\u5bc6\u7801\u4e0d\u5b89\u5168").show();break;case "INVALID_PWD":a("#newPasswordTip").html("\u5bc6\u7801\u4e0d\u7b26\u5408\u89c4\u8303").show();
break;case "INVALID_PWD_NEW":a("#newPasswordTip").html("\u7cfb\u7edf\u7981\u6b62\u4f7f\u7528\u524d3\u6b21\u7528\u8fc7\u7684\u5bc6\u7801").show();break;default:b.comm.alert("\u8bbe\u7f6e\u5bc6\u7801\u5931\u8d25")}},dataType:"json",fnFail:function(){b.getFailTip()}})},goPassSuc:function(){this.vdpwd=null;a("#setPassSuc").show();a("#setNewPassword").hide();this.initPassSuc()},initPassSuc:function(){var b=this;a("#newLogin").unbind().bind("click",function(a){b.comm.goLogin();a.stopPropagation();return!1});
b.isPhone?a("#topTip").html("\uff08\u624b\u673a\u77ed\u4fe1\u9a8c\u8bc1\uff09"):b.isQuestion&&a("#topTip").html("\uff08\u5b89\u5168\u95ee\u9898\u9a8c\u8bc1\uff09")},checkPass:function(){var b=a("#newPassword").val(),c=a("#comfirmPassword").val(),d=a("#newPasswordTip"),f=a("#comfirmPasswordTip");d.hide();f.hide();if(parseInt(this.vdpwd.NotifyCode,10)!==0)return d.html(this.vdpwd.msg).show(),!1;if(this.comm.checkEmpty(c))return f.html("\u786e\u8ba4\u5bc6\u7801\u4e0d\u80fd\u4e3a\u7a7a").show(),!1;if(b!==
c)return f.html("\u4e24\u6b21\u8f93\u5165\u7684\u5bc6\u7801\u4e0d\u4e00\u81f4\uff0c\u8bf7\u91cd\u65b0\u8f93\u5165").show(),!1;this.password=b;return!0},getCode:function(){jQuery("#getCode");this.codeHtml='<var id="codeSec">60</var>\u79d2\u540e\u53ef\u91cd\u65b0\u83b7\u53d6\u77ed\u4fe1\u9a8c\u8bc1\u7801';i=60;this.checkCodePic()&&this.ajaxGetCode()},checkCodePic:function(){var b=a("#"+("safeQuestion"==this.getWay?"picCode_answer":"picCode")).val().trim();a("#msCodeTip").hide();this.picCode=b;return this.comm.checkEmpty(b)?
(a("#picCodeTip").html("\u56fe\u7247\u9a8c\u8bc1\u7801\u4e0d\u80fd\u4e3a\u7a7a").show(),!1):!0},setCodeInterval:function(){var a=this,c=jQuery,d=59,f=c("#getCode");a.timer=setInterval(function(){d?(c("#codeSec").html(d--),f.unbind("click").bind("click",function(a){a.stopPropagation();return!1})):(anewSpan='<span id="">\u91cd\u65b0\u83b7\u53d6\u9a8c\u8bc1\u7801</span>',c("#getCode").attr("class",a.comm.className.codeNormal),f.html(anewSpan),a.clearCodeInterval(),a.initGetCode())},1E3)},clearCodeInterval:function(){if(this.timer)clearInterval(this.timer),
this.timer=null;a("#getCode").html("\u91cd\u65b0\u53d1\u9001\u77ed\u4fe1\u9a8c\u8bc1\u7801");a("#getCode").attr("class",this.comm.className.codeNormal);this.initGetCode()},ajaxGetCode:function(){var a=this,c=jQuery,d={mobilePhone:a.mobilePhone,code:a.picCode},f=null,f=null,g=c("#getCode");c("#getCodeTip,#picCodeTip").hide();url=a.comm.url.webPath+"/service/common/validate.do?func="+a.comm.func.GetMobileValidateCode;a.comm.doService({type:"POST",url:url,data:d,fnSuc:function(d){d.code.toUpperCase()==
"S_OK"?(g.html(a.codeHtml),a.getcodeDisabled(),a.setCodeInterval(),c("#msCode").focus()):(d.code.toUpperCase()=="INVALID_VERIFY_CODE"?c("#picCodeTip").text("\u56fe\u7247\u9a8c\u8bc1\u7801\u9519\u8bef\uff0c\u8bf7\u91cd\u65b0\u8f93\u5165").show():(a.initGetCode(),c("#getCodeTip").text("\u83b7\u53d6\u9a8c\u8bc1\u7801\u5931\u8d25").show()),a.comm.refreshImgRndCode())},fnFail:function(){a.initGetCode();c("#getCodeTip").text("\u83b7\u53d6\u9a8c\u8bc1\u7801\u5931\u8d25").show();a.comm.refreshImgRndCode()},
dataType:"json"})},comm:{drag:function(a,c){a.onmousedown=function(d){var f=d||event,g=f.clientX-a.offsetLeft-176,k=f.clientY-a.offsetTop-70,h=document,j=window;a.style.position="absolute";if(c)a.style.zIndex=++c;a.setCapture?a.setCapture():j.captureEvents&&j.captureEvents(f.MOUSEMOVE);h.onmousemove=function(c){c=c||event;a.style.left=c.clientX-g+"px";a.style.top=c.clientY-k+"px"};h.onmouseup=function(){a.releaseCapture?a.releaseCapture():j.captureEvents&&j.releaseEvents(f.MOUSEMOVE);h.onmousemove=
null;h.onmouseup=null};return!1}},goBack:function(a){a.click(function(){window.location.go(-1);return!1})},resetProperty:function(){var a=d;a.isPhone=!1;a.isQuestion=!1;a.mobilePhone="";a.picCode="";a.mailAccount="";a.safeQuestion="";a.answer=""},goLogin:function(){window.location.href=constant.webPath+"/login/login.do"},hideAll:function(){a("#choiseWay,#vdEmail,#vdPhone,#vdQuestion,#setNewPassword,#setPassSuc").hide()},alert:function(b,c,e){var f=a("#dialog"),g=a("#mask"),k=d;a("#picCode").blur();
f.show();g.show();k.comm.drag(a("#dialog")[0]);a("#closeDialog,#dialogOk").click(function(){f.hide();g.hide()});a("#dContent").html(b);c&&f.css("width",c);e&&f.css("height",e);a(document).keyup(function(a){if(a.which==13)return f.hide(),g.hide(),!1})},func:{ValidateUserCode:"common:ValidateUserCode",GetUserSecurityConf:"mail:GetUserSecurityConf",ValidateMobileCode:"common:ValidateMobileCode",GetMobileValidateCode:"common:GetMobileValidateCode",UpdateUserPassword:"common:UpdateUserPassword",ValidateUserQuestion:"common:ValidateUserQuestion"},
className:{codeNormal:"secondBtn",codeGray:"secondBtn_un"},url:{webPath:constant.webPath},changCurrent:function(b){a("#topStep")[0].src="images/step"+b+".jpg"},checkEmpty:function(a){return/^\s*$/.test(a)?!0:!1},checkPhone:function(){},encodeHTML:function(a){a=a.replace(/&/g,"&amp;");a=a.replace(/</g,"&lt;");a=a.replace(/>/g,"&gt;");a=a.replace(/\"/g,"&quot;");a=a.replace(/ /g,"&nbsp;");return a=a.replace(/\'/g,"&#39;")},checkMobile:function(a){return/^(86)?((13[4-9]{1})|(15[0-2 7-9]{1})|(18[2 7-8]{1}))+\d{8}$/.test(a)},
checkData:function(a,c,d){var c=c.toString().replace(/^\s+|\s+$/,""),f="";switch(a){case "email":f=/^([A-Z0-9._%-]{1,255})@[A-Z0-9._%-]+\.[A-Z0-9]{1,4}$/i;break;case "mobile":f=/^(0?86)?1[\d]{10}$/i;break;case "phone":f=/^0[\d]{2,3}[\d]{7,8}$/i;break;case "empty":f=/^.+/i;break;case "number":case "int":f=/^[0-9]+$/i;break;case "domain":f=/^[A-Z0-9._%-]+\.[A-Z0-9]{1,4}$/i;break;case "blackDomain":f=/^(\*@)[A-Z0-9._%-]+\.[A-Z0-9]{1,4}$/i;break;case "*@domain":f=/^(\*@)[A-Z0-9._%-]+\.[A-Z0-9]{1,4}$/i;
break;case "@domain":f=/^(@)[A-Z0-9._%-]+\.[A-Z0-9]{1,4}$/i;break;case "port":return c>0&&c<65535?!0:!1;case "reg":f=d;break;case "custom":f=RegExp(d,"gi")}try{return f?f.test(c):!1}catch(g){return!1}},doService:function(b){a.ajax({type:b.type||"POST",url:b.url||"",data:JSON.stringify(b.data),dataType:"json",contentType:"text/javascript; charset=UTF-8",success:b.fnSuc,error:b.fnFail})},refreshImgRndCode:function(b){a("#"+(b||"imgRnd"))[0].src=constant.imgUrl+"?r="+(new Date).getTime()},defautEvent:function(b,
c){b.focus(function(){this.value.replace(/^\s+|\s+$/,"")===c&&a(this).val("")});b.blur(function(){this.value.replace(/^\s+|\s+$/,"")===""&&a(this).val(c)})}}};window.setPassword=d})(jQuery);setPassword.init();
